/*
 * Language initialization (LangInit) GUI class.
 */
package gecko;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import i18n.DoubleMap;
import bot.DLbot;

/**
 *
 * @author Nicholas Eyring
 */
public class LangInit extends javax.swing.JFrame {
    
    public static GeckoGUI app;
    
    public static String language;
    
    public static DoubleMap englishMap; // English map
    public static DoubleMap transMap ; // Translated map

    /**
     * Creates new form LangInit
     */
    public LangInit() {
        initComponents();
        setLocationRelativeTo(null); // display in center-screen
        setResizable(false);
        
        // "Exit" button
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new InitDialog().setVisible(true); // confirm exit
            }
        });
        
        // "Continue" button
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                language = jComboBox1.getSelectedItem().toString();
                initEnglishMap(); // initialize englishMap
                if (!language.equals("English")) {
                    transMap = DLbot.getTranslations(); // initialize transMap
                } else {
                    transMap = englishMap; // use englishMap if English is chosen
                }
                app = new GeckoGUI();// create the Gecko GUI
                app.setVisible(true);
                dispose();
            }
        });
    }
    
    private void initEnglishMap(){
        englishMap = new DoubleMap(); // create a new DoubleMap
        // initialize KeytoValue
        englishMap.KeytoValue.put("GeckoFrame.jMenu1.text", "File");
        englishMap.KeytoValue.put("GeckoFrame.jMenuItem1.text", "New");
        englishMap.KeytoValue.put("GeckoFrame.jMenuItem2.text", "Save");
        englishMap.KeytoValue.put("GeckoFrame.jMenuItem3.text", "Open");
        englishMap.KeytoValue.put("GeckoFrame.jMenuItem4.text", "Exit");
        englishMap.KeytoValue.put("GeckoFrame.jMenuItem8.text", "Save As");
        englishMap.KeytoValue.put("GeckoFrame.jMenuItem9.text", "Save as Applet");
        englishMap.KeytoValue.put("GeckoFrame.jMenuItem10.text", "Save View as Image");
        
        // initialize ValuetoKey
        englishMap.ValuetoKey.put("File", "GeckoFrame.jMenu1.text");
        englishMap.ValuetoKey.put("New", "GeckoFrame.jMenuItem1.text");
        englishMap.ValuetoKey.put("Save", "GeckoFrame.jMenuItem2.text");
        englishMap.ValuetoKey.put("Open", "GeckoFrame.jMenuItem3.text");
        englishMap.ValuetoKey.put("Exit", "GeckoFrame.jMenuItem4.text");
        englishMap.ValuetoKey.put("Save As", "GeckoFrame.jMenuItem8.text");
        englishMap.ValuetoKey.put("Save as Applet", "GeckoFrame.jMenuItem9.text");
        englishMap.ValuetoKey.put("Save View as Image", "GeckoFrame.jMenuItem10.text");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please choose a language:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Deutsch", "Français", "Italiano" }));

        jButton1.setText("Exit");

        jButton2.setText("Continue");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LangInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LangInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LangInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LangInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LangInit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
